---

- name: block with sudo escalation
  become_user: root
  become: true
  block:

    # - name: "add letsencrypt repository for certbot"
    #   apt_repository:
    #     repo: ppa:certbot/certbot
    #     state: present
     
    - name: "install nginx and letsentcrypt packages"
      apt:
        pkg:
          - apache2-utils
          - nginx
          - python3-certbot-nginx
          - libnginx-mod-http-headers-more-filter
        state: latest
        update_cache: yes

    - name: "Copying the 'nginx.conf' file into the /etc/nginx directory"
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: 0644
        owner: root
        group: root

    - name: "check if letsencrypt has installed certificate already and therefore nginx is already installed"
      stat: 
        path: /etc/letsencrypt/live
      register: le_cert_dir

    - name: "Block that only executes if letsencrypt didn't retrieve any certs yet"
      block:

        - name: "copying nginx default host config"
          template: 
            src:  vhost.initial.conf.j2
            dest: "{{ nginx.vhost_default_file }}"
         
        - name: "making sure that the directory '{{ nginx.base_directory }}' exists"
          file:
            path: "{{ nginx.base_directory }}"
            state: directory
    
        - name: "runnig certbot and obtaining ssl certs if it didn't run yet"
          shell: "certbot --nginx {{ certbot.domain_string }} -m {{ certbot.contact_email }} --non-interactive --agree-tos"
          notify: restart nginx

        - name: "setting nginx base directory's owner:group '{{ nginx.base_directory }}' recursively to {{ nginx.owner }}:{{ nginx.group }}"
          file:
            path: "{{ nginx.base_directory }}"
            state: directory
            owner: "{{ nginx.owner }}"
            group: "{{ nginx.group }}"
            recurse: yes
          notify:
            - restart nginx

      when: le_cert_dir.stat.exists == false
      # End of block

    - name: "Block that only executes if letsencrypt already retrieved certs"
      block:

        - name: "copy nginx default host config"
          template: 
            src:  vhost.update.conf.j2
            dest: "{{ nginx.vhost_default_file }}"
          notify:
            - restart nginx

      when: le_cert_dir.stat.exists == true