---

- name: "Stopping consul service if already installed"
  become: yes
  systemd:
    name: consul
    state: stopped
  ignore_errors: yes

# Start CentOS Block
- name: "Block for CentOS servers"
  become: yes
  block:

    - name: "Adding consul user 'consul'"
      become: yes
      user:
        name: consul

    - name: "Creating consul directory /opt/consul"
      become: yes
      file:
        path: /opt/consul
        state: directory
        owner: consul

    - name: "Creating consul working directory /var/lib/consul"
      become: yes
      file:
        path: /var/lib/consul
        state: directory
        owner: consul

    - name: "Downloading consul zip"
      become: yes
      get_url:
        url: https://releases.hashicorp.com/consul/1.0.7/consul_1.0.7_linux_amd64.zip
        dest: /tmp/consul.zip

    - name: "Creating consul config directory /etc/consul.d"
      become: yes
      file:
        path: /etc/consul.d
        state: directory

    - name: "Extracting consul zip"
      become: yes
      unarchive:
        src: /tmp/consul.zip
        dest: /opt/consul/
        owner: consul
        remote_src: True

    - name: "Installing consul systemd unit"
      become: yes
      copy:
        src: consul.service
        dest: /etc/systemd/system/consul.service

  when: ansible_facts['distribution'] == "CentOS"
# End CentOS Block

# Start Debian Block
- name: "Block for Debian servers"
  become: yes
  block:
    - name: "Installing consul with apt"
      become: yes
      apt:
        name: consul

  when: ansible_facts['distribution'] == "Debian"
# End Debian Block

- name: "Installing consul config"
  become: yes
  template:
    src: consul_config.json.j2
    dest: /etc/consul.d/config.json
    owner: consul
    mode: 0644

- name: "Starting consul service"
  become: yes
  systemd:
    name: consul
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: "Waiting 60 seconds for consul application port 8500 to open"
  become: yes
  wait_for:
    port: 8500
    timeout: 60


# Todo - Health check
