---
- name: "Run with python 2 as root"
  become: yes
  vars:
    ansible_python_interpreter: "{{ ansible_python2_interpreter }}"
  block:
    - name: Remove the test database
      mysql_db:
        name: test
        login_user: root
        state: absent

    - name: Create user defined databases
      mysql_db:
        name: "{{ item.name }}"
        login_user: root
        state: present
      with_items: "{{ mariadb_databases }}"
