---
ansible_python_interpreter: /usr/bin/python3
ansible_python2_interpreter: /usr/bin/python2

certbot_contact_email: "your.personal,email@your-companies-domain82347.com"

nginx:
  document_root: /var/www/html
  basic_auth_file: /etc/nginx/passwd
  Ubuntu:
    owner: www-data
    group: www-data
  Debian:
    owner: www-data
    group: www-data
  CentOS:
    owner: nginx
    group: nginx

packages:
  present:
    # generic packages are OS-independant packages
    generic:
      common:
        - curl
        - net-tools
        - python3-pip
        - telnet
        - tree
        - unzip
        - vim
    Debian:
      # as of now, we don't have any Debian-specific common packages
      common:
      nginx:
        - nginx
        - software-properties-common
        - python-certbot-nginx
        - python-passlib
        - httpd-tools
    CentOS:
      common:
      docker:
        - device-mapper-persistent-data
        - lvm2
        - yum-utils
        - docker-ce
        - docker-ce-cli
        - containerd.io
      java:
        - java-11-openjdk.i686
      nginx_pre:
        - epel-release
      nginx:
        - nginx.x86_64
        - certbot-nginx
        - python-passlib
        - httpd-tools
  absent:
    generic:
      common:
    Ubuntu:
      common:
    Debian:
      common:
    CentOS:
      common:

timezone: "Europe/Berlin"
