---
fpm: 
  php_ini: "/etc/php/{{ php.version }}/fpm/php.ini"
  socket_string: "unix:/run/php/php{{ php.version }}-fpm.sock"

nginx:
  base_directory: /var/www/html
  owner: www-data
  group: www-data
  vhost_default_file: /etc/nginx/sites-available/default

revive_version: 5.0.5
revive:
  download_url: https://download.revive-adserver.com/revive-adserver-{{ revive_version }}.tar.gz
  download_dir: /tmp

php:
  version: "7.4"

system:
  packages:
    present:
      - build-essential
      - dnsutils
      - inetutils-traceroute
      - libsasl2-modules
      - mysql-client
      - net-tools
      - pcregrep
      - "python3-pymysql"
      - "php{{ php.version }}"
      - "php{{ php.version }}-cli"
      - "php{{ php.version }}-curl"
      - "php{{ php.version }}-fpm"
      - "php{{ php.version }}-gd"
      - "php{{ php.version }}-imagick"
      - "php{{ php.version }}-intl"
      - "php{{ php.version }}-json"
      - "php{{ php.version }}-mbstring"
      - "php{{ php.version }}-mysql"
      - "php{{ php.version }}-opcache"
      - "php{{ php.version }}-soap"
      - "php{{ php.version }}-xml"
      - "php{{ php.version }}-xmlrpc"
      - "php{{ php.version }}-zip"
      - python3-pip
      - python3-boto
      - python3-boto3
      - python3-botocore
      - python3-dev
      - python3-pip
      - software-properties-common
      - traceroute
      - unzip
      - vim
    absent:
      - apache2
      - ufw

timezone: Europe/Berlin