---
- name: "Syncing ssh keys for '{{ inventory_file.split('/') | last }}'-Environment if we are on a remote server"
  block:
    - name: "Syncing authorized ssh keys for '{{ inventory_file.split('/') | last }}'-Environment"
      authorized_key:
        user: "{{ hostvars[inventory_hostname].ansible_ssh_user }}"
        key: "{{ item }}"
        state: present
        # do not remove non-specified keys from existing file. 
        # with the following line, we specify, that we only make
        # sure that the SSH keys form our file are present. We
        # ignore any additional SSH keys that might have been
        # provisioned otherwise
        exclusive: no
      with_file:
        - "{{ inventory_file.split('/') | last }}_adesso_ssh_keys_present"
    
    - name: "Removing unauthorized ssh keys for user {{ hostvars[inventory_hostname].ansible_ssh_user }}@{{ inventory_hostname }}"
      authorized_key:
        user: "{{ hostvars[inventory_hostname].ansible_ssh_user }}"
        key: "{{ item }}"
        state: absent
      with_file:
        - "{{ inventory_file.split('/') | last }}_adesso_ssh_keys_absent"
  when: ansible_ssh_host != "127.0.0.1"\