---

- name: get service facts to make sure there is no mariadb installed already
  service_facts:

# Start CentOS Block
- name: "Block for CentOS servers - run only when `mariadb.service` is not defined"
  become: yes
  vars:
    ansible_python_interpreter: "{{ ansible_python2_interpreter }}"
  block:

    - name: "Installing MariaDB.repo"
      copy:
        src: MariaDB.repo
        dest: /etc/yum.repos.d/MariaDB.repo

    - name: Install MariaDB
      yum:
        update_cache: yes
        name:
          - MariaDB-common
          - MariaDB-server
          - MySQL-python
        state: latest

    - name: Install network config file
      template:
        src: etc_my.cnf.d_network.cnf.j2
        dest: /etc/my.cnf.d/network.cnf
      notify: restart mariadb

    - name: Configure logrotate
      template:
        src: etc_logrotate.d_mysql.j2
        dest: /etc/logrotate.d/mysql
      when: mariadb_logrotate.configure|bool
      notify: restart mariadb

    - name: Ensure service is started
      service:
        daemon_reload: yes
        name: mariadb
        state: started
        enabled: true

  when: ansible_facts['distribution'] == "CentOS" and ansible_facts.services["mariadb.service"] is not defined
# End CentOS Block
