---

- name: "Adding webapp user"
  become: yes
  user:
    name: "{{ webapp.user }}"

- name: "Creating content directory"
  become: yes
  file:
    path: "{{ webapp.content_path }}"
    state: directory
    owner: "{{ webapp.user }}"

- name: "Installing rsyncd conf"
  become: yes
  template:
    src: rsyncd_content.conf.j2
    dest: /etc/rsyncd.conf

- name: "(Centos) (Re-)starting rsyncd service"
  become: yes
  systemd:
    name: rsyncd
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: ansible_facts['distribution'] == "CentOS"

- name: "(Debian) (Re-)starting rsync service"
  become: yes
  systemd:
    name: rsync
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: ansible_facts['distribution'] == "Debian"