---

- name: "Block for Debian servers"
  become: yes
  block:

    - name: "Installing Debian-specific java"
      apt:
        name: "{{ packages.present.Debian.java }}"
        state: latest

  when: ansible_facts['distribution'] == "Debian"

- name: "Block for CentOS servers running yum"
  become: yes
  vars:
    ansible_python_interpreter: "{{ ansible_python2_interpreter }}"
  block: 

    - name: "Installing CentOS-specific packages with yum"
      yum:
        name: "{{ packages.present.CentOS.java }}"
        state: latest

  when: ansible_facts['distribution'] == "CentOS"
