version: '3'

services:

  solr_1:
    container_name: solr_1
    image: solr_8
    build: ./solr
    environment:
      - ZOO_NODE=1
    ports:
      - "8983:8983"
      - "2181:2181"
    depends_on:
      - solr_2
      - solr_3
    restart: always

  solr_2:
    container_name: solr_2
    image: solr_8
    build: ./solr
    environment:
      - ZOO_NODE=2
    ports:
      - "8984:8983"
      - "2182:2181"
    restart: always

  solr_3:
    container_name: solr_3
    image: solr_8
    build: ./solr
    environment:
      - ZOO_NODE=3
    ports:
      - "8985:8983"
      - "2183:2181"
    restart: always
