---
- name: "Tearing down any existing docker services"
  become: yes
  docker_compose:
    project_src: /opt/solr/
    state: absent
  ignore_errors: yes

- name: "Copying solr configuration for docker"
  become: yes
  synchronize:
    delete: yes
    src: .
    dest: /opt/solr/

- name: "Creating and starting services"
  become: yes
  docker_compose:
    project_src: /opt/solr/
    build: true
