---

- name: "Block for Debian servers"
  become: yes
  block:

    - name: "Updating all installed packages"
      apt:
        upgrade: 'yes'
        update_cache: yes

    - name: "Updating apt cache and installing generic packages"
      apt:
        name: "{{ packages.present.generic.common }}"
        state: latest

    # - name: "Installing Debian-specific packages with apt"
    #   apt:
    #     name: "{{ packages.present.Debian.common }}"
    #     state: latest

    - name: "Uninstalling generic packages with apt"
      apt:
        name: "{{ packages.absent.generic.common }}"
        state: absent

    - name: "Uninstalling Debian-specific packages with apt"
      apt:
        name: "{{ packages.absent.Debian.common }}"
        state: absent

  when: ansible_facts['distribution'] == "Debian"


- name: "Block for CentOS servers running yum"
  become: yes
  vars:
    ansible_python_interpreter: "{{ ansible_python2_interpreter }}"
  block:

    - name: "Updating all yum-installed packages"
      yum:
        name: "*"
        update_cache: yes
        state: latest

    - name: "Installing generic packages with yum"
      yum:
        name: "{{ packages.present.generic.common }}"
        state: latest

    # - name: "Installing CentOS-specific packages with yum"
    #   yum:
    #     name: "{{ packages.present.CentOS.common }}"
    #     state: latest

    - name: "Uninstalling generic packages with yum"
      yum:
        name: "{{ packages.absent.generic.common }}"
        state: absent

    - name: "Uninstalling CentOS-specific packages with yum"
      yum:
        name: "{{ packages.absent.CentOS.common }}"
        state: absent

  when: ansible_facts['distribution'] == "CentOS"

# Generic tasks, that have to run on all servers
#
- name: "Setting timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  become: yes
