---

- name: Block with sudo escalation
  become_user: root
  become: yes
  block:

    - name: Update all installed packaged system
      apt: 
        upgrade: yes 
        update_cache: yes
      
    - name: install base packages
      apt:
        name: "{{ system.packages.present }}"
        state: latest

    - name: uninstall unnecessary packages
      apt:
        name: "{{ system.packages.absent }}"
        state: absent

    - name: set timezone
      timezone:
        name: "{{ timezone }}"
