---
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_ssh_host: 127.0.0.1
ansible_ssh_port: 2202
ansible_ssh_user: vagrant
ansible_ssh_private_key_file: .vagrant/machines/debian/virtualbox/private_key
app_user: "root"
bind_ip: "10.10.10.10"
# Overriding the global number of 3 expected servers as set in ~/group/vars/all/config.yml
# in our VMs, all we need is 1
consul_bootstrap_expect: 1
java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
nginx_server_names: 
  - "lmwr-edge01.test-server.ag"
  - "lmwr.test-server.ag"
profile: "local"
