---
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "ubuntu"
ansible_ssh_host: lmrv.ml
ansible_ssh_private_key_file: "~/.ssh/smings"

certbot:
  domain_string: "-d lmrv.ml -d ad.lmrv.ml -d www.lmrv.ml"
  contact_email: "letsencrypt-certs@smings.com"

dns_names: "lmrv.ml ad.lmrv.ml www.lmrv.ml"

# This is always the first domain that is passed on to the certbot
letsencrypt_cert_dir: lmrv.ml
